# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0xd5c4a1ff
rootcolor = 0xfbf1c7ff
bordercolor = 0x9e8861ff
focuscolor = 0x98971aff
maximizescreencolor = 0xd79921ff
urgentcolor = 0xcc241dff
scratchpadcolor = 0x458588ff
globalcolor = 0xd9d98bff
overlaycolor = 0xecdcbfff
